### ISSUE TITLE
Mining nodes not showing on map

### ISSUE THREAD

**Issue by jowhite83** [syndenbock/Farmer#5] opened 2022-09-08 23:21 UTC
In WotLK Classic, mining nodes are not showing on the map despite being there,

**Comment by syndenbock** [comment] 2022-09-09 01:49
Does this refer to the farmradar feature?
And are we talking about the default yellow circles or icons from another addon?

**Comment by syndenbock** [comment] 2022-10-11 21:37
Duplicate of #6

**Closed as not planned by syndenbock** 2022-10-11 21:37 UTC
Labels: bug, duplicate
