### ISSUE TITLE
Farmer move command won't work

### ISSUE THREAD

**Issue by geggiot** [syndenbock/Farmer#19] opened 2024-08-25 17:08 UTC
hi,
can't move message frame with /farmer move command in chat or pressing move display button in option.
This is message error

Message: ...AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua:555: attempt to call upvalue 'transformFrameAnchorsToCenter' (a nil value)
Time: Sun Aug 25 19:01:14 2024
Count: 1
Stack: ...AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua:555: attempt to call upvalue 'transformFrameAnchorsToCenter' (a nil value)
[string "@Interface/AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua"]:555: in function `Move'
[string "@Interface/AddOns/Farmer/main/Options.lua"]:50: in function `handler'
[string "@Interface/AddOns/Farmer/utils/SlashCommands.lua"]:25: in function <Interface/AddOns/Farmer/utils/SlashCommands.lua:18>
[string "@Interface/AddOns/Farmer/utils/SlashCommands.lua"]:33: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function <...AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5414>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function <...AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5119>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function <...AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5152>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals: self = <table> {
 fading = true
 shadowOffset = <table> {
 }
 ALIGNMENT_LEFT = "LEFT"
 visibleTime = 3
 fontFlags = "OUTLINE"
 resetCallbacks = <table> {
 }
 spacing = 2
 mode = <table> {
 }
 subspaceCount = 5
 fadeDuration = 1
 INSERTMODE_APPEND = "APPEND"
 insertMode = "PREPEND"
 GROW_DIRECTION_DOWN = "DOWN"
 anchor = Frame {
 }
 shadowColors = <table> {
 }
 alignment = "CENTER"
 direction = "UP"
 messageInfo = <table> {
 }
 GROW_DIRECTION_UP = "UP"
 subspaces = <table> {
 }
 iconSize = 24
 framePool = <table> {
 }
 iconScale = 1
 font = "Interface\AddOns\ElvUI\Core\Media\Fonts\Expressway.ttf"
 fontSize = 24
 INSERTMODE_PREPEND = "PREPEND"
 ALIGNMENT_RIGHT = "RIGHT"
 ALIGNMENT_CENTER = "CENTER"
}
icon = 134435
text = "Farmer Anchor"
message = Frame {
 animationGroup = AnimationGroup {
 }
 iconFrame = ARTWORK {
 }
 PixelSnapDisabled = true
 animation = Alpha {
 }
 fontString = FontString {
 }
}
(*temporary) = nil
(*temporary) = Frame {
}
(*temporary) = "attempt to call upvalue 'transformFrameAnchorsToCenter' (a nil value)"
transformFrameAnchorsToCenter = nil

**Comment by syndenbock** [comment] 2024-08-25 19:15
Thanks for reporting this, it should work again iin version 3.25.3 that I just released.
Could you please verify it works now and if so, close this issue?

**Comment by geggiot** [comment] 2024-08-25 19:33
> Thanks for reporting this, it should work again iin version 3.25.3 that I just released. Could you please verify it works now and if so, close this issue?

now i can move display frame but got this error after release left mouse button to move it
Message: Attempted to release inactive object 'table: 00000235EC3D1770'
Time: Sun Aug 25 21:30:06 2024
Count: 1
Stack: Attempted to release inactive object 'table: 00000235EC3D1770'
[string "@Interface/AddOns/Blizzard_SharedXMLBase/Pools.lua"]:79: in function `Release'
[string "@Interface/AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua"]:259: in function <...AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua:257>
[string "@Interface/AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua"]:267: in function <...AddOns/Farmer/widgets/MessageFrames/MessageFrame.lua:266>

Locals: self = <table> {
 activeObjects = <table> {
 }
 activeObjectCount = 1
 capacity = Infinite
 inactiveObjects = <table> {
 }
}
object = Frame {
 animationGroup = AnimationGroup {
 }
 animation = Alpha {
 }
 PixelSnapDisabled = true
 iconFrame = ARTWORK {
 }
 fontString = FontString {
 }
}
canFailToFindObject = nil
active = false

**Comment by syndenbock** [comment] 2024-08-25 19:48
I may have an idea what the issue is but I couldn't reproduce it yet. But the moving itself should work just fine, correct?

**Comment by geggiot** [comment] 2024-08-25 19:50
Yessir move frame works now

**Comment by syndenbock** [comment] 2024-08-25 20:09
I will close this as completed then as the other error is unrelated to moving the frame.

**Closed as completed by syndenbock** 2024-08-25 20:09 UTC
Labels: bug
