### ISSUE TITLE
BUG in Currencies/lua line 50 on 9.0.1 (Patch day)

### ISSUE THREAD

**Issue by Voraga** [syndenbock/Farmer#1] opened 2020-10-14 00:59 UTC
With the 9.0.1 patch I am getting this error. Hope this helps get this addon up and running because I love the popup loot messages.

`Message: Interface\AddOns\Farmer\detectors\Currencies.lua:50: attempt to call upvalue 'GetCurrencyListSize' (a nil value)
Time: Tue Oct 13 18:55:13 2020
Count: 1
Stack: Interface\AddOns\Farmer\detectors\Currencies.lua:50: attempt to call upvalue 'GetCurrencyListSize' (a nil value)
[string "@Interface\AddOns\Farmer\detectors\Currencies.lua"]:50: in function `callback'
[string "@Interface\AddOns\Farmer\classes\CallbackHandler.lua"]:88: in function `call'
[string "@Interface\AddOns\Farmer\core\Events.lua"]:11: in function <Interface\AddOns\Farmer\core\Events.lua:10>

Locals: data = <table> {
}
expandedIndices = <table> {
}
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetCurrencyListSize' (a nil value)"
GetCurrencyListSize = nil
GetCurrencyListInfo = nil
tinsert = <function> defined =[C]:-1
ExpandCurrencyList = nil
GetCurrencyListLink = nil
GetCurrencyIDFromLink = <function> defined =[C]:-1
collapseExpandedCurrencies = <function> defined @Interface\AddOns\Farmer\detectors\Currencies.lua:39
HONOR_ID = 1792
getCurrencyAmount = <function> defined @Interface\AddOns\Farmer\detectors\Currencies.lua:33
CONQUEST_ID = 1602
currencyTable = nil
`

**Comment by syndenbock** [comment] 2020-10-14 08:48
This was caused by the API changes in the 9.0 prepatch and fixed in version 3.4.

**Closed as completed by syndenbock** 2020-10-14 08:48 UTC
Labels: bug
