### ISSUE TITLE
GatherMate icons disappearing from radar

### ISSUE THREAD

**Issue by fernando-marquardt** [syndenbock/Farmer#6] opened 2022-09-20 14:54 UTC
When farming with the radar ON, it shows the GatherMate icons correctly, but after some time, they start to disappear. Icons previously visible start to disappear and new ones (lets say I find a new node) don't appear in the radar. Not all icons disappear, but I can't find a pattern to reason which ones do.

The real nodes are still visible (the yellow dots), only the GatherMate images disappear. And they are still visible in the main map.

I know the addon uses some tricks with the minimap, right? So I made some testing, and when with the minimap ON and the radar OFF, no icons seem to disappear in the minimap.

**Comment by syndenbock** [comment] 2022-09-23 10:25
That is a rather strange behaviour as the radar itself doesn't do any more "tricks" with the minimap while the radar is enabled.
Do you have the "show GatherMate nodes" option enabled? If not, the nodes visible on the minimap at that time are being hidden and when GatherMate "recycles" these nodes to create new nodes they are still hidden.

**Comment by fernando-marquardt** [comment] 2022-09-23 11:44
Just checked, and the SHow GatherMate Nodes option is active. At some point I tought that maybe the icons were being removed because the addon (not sure if Farmer or GatherMate) was, as you said, recycling the icons, but the radar was not reloading them into the radar.

Because at first, all icons seem to be visible, they start to disappear after some time running around the map, but not all icons disappear (so if I leave an area with some 5 nodes, when I come back maybe 2 or 3 disappeared). And running some long runs, eventually all icons disappear.

If I disable the radar and reenable, nothing happens, ~~only the full UI reload fixes this temporaly.~~

Edit: Actually, just checked that between a session and another (logging out, changing to another character and logging back to the miner character), a few nodes start hidden and they don't show back after mining the node (GatherMate usually updates the node position everytime). They are in the map, only the radar is unable to show them.

Mining or not a node, does not seem to have an effect over it disappearing. Some that I mined disappeared in the next run, others disappeared without ever being touched.

**Comment by syndenbock** [comment] 2022-09-23 21:09
I did some testing with GatherMate and I think I found the issue, but I don't know how to properly work around it, especially not without creating huge memory and cpu overhead.

**Comment by fernando-marquardt** [comment] 2022-09-26 01:17
What is the issue? Maybe I could try to come with some idea

**Comment by syndenbock** [comment] 2022-10-05 22:49
Sorry for the late response, I'm kinda busy atm.
For retail I actually found the perfect fix thanks to a new API function they added for the minimap.
Unfortunately on all other flavors this API doesn't exist (yet).

For those flavors the issue is that, in order to hide the minimap background I need to set the minimaps alpha to 0. The background itself is not accessible (at least I didn't find anything) so it has to be the minimap itself. This causes all of the minimaps children, which includes the GatherMate icons, to also gain an alpha of 0. This can be prevented by using "SetIgnoreParentAlpha".
And here is where the issue occurs: When GatherMate creates new icons while the farmradar is active, the addon has no clean/performant way of detecting those icons and setting SetIgnoreParentAlpha.
Currently the addon doesn't detect these icons at all which makes it look like icons disappear when they get reused in the icon pool

**Comment by syndenbock** [comment] 2022-10-11 21:36
I have implemented a solution for Classic aswell, so I'm closing this. If the issue reappears please open another issue. I don't play Classic myself, so I won't notice if something breaks there.

**Closed as completed** 2022-10-11 21:35 UTC
