### ISSUE TITLE
Error When I login or Reload

### ISSUE THREAD

**Issue by Comicus** [syndenbock/Farmer#14] opened 2022-12-10 07:57 UTC
2x Farmer error: Interface\AddOns\Farmer\classes\Storage.lua:77: table index is nil
[string "@Interface\AddOns\Farmer\core\Events.lua"]:29: in function <Interface\AddOns\Farmer\core\Events.lua:25>
[string "=[C]"]: in function `pcall'
[string "@Interface\AddOns\Farmer\utils\Utils.lua"]:123: in function <Interface\AddOns\Farmer\utils\Utils.lua:122>
[string "@Interface\AddOns\Farmer\classes\CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Interface\AddOns\Farmer\classes\CallbackHandler.lua"]:48: in function `call'
[string "@Interface\AddOns\Farmer\core\Events.lua"]:10: in function <Interface\AddOns\Farmer\core\Events.lua:9>

**Comment by syndenbock** [comment] 2022-12-10 13:37
Are you playing Classic, Wrath or Retail?
Is this happening on all your characters or only on one?
And would you mind uploading a screenshot of your current equipment and your bags?
It seems an item in your equipment or your bags returns empty information causing this error.

**Comment by WorkPixels** [comment] 2022-12-15 23:34
WoW Classic WotLK
Version 3.4.0.46902

App Version
Farmer-3.16.5

27x Farmer error: Interface\AddOns\Farmer\classes\Storage.lua:90: table index is nil
[string "@Interface\AddOns\Farmer\core\Events.lua"]:29: in function <Interface\AddOns\Farmer\core\Events.lua:25>
[string "=[C]"]: in function `pcall'
[string "@Interface\AddOns\Farmer\utils\Utils.lua"]:123: in function <Interface\AddOns\Farmer\utils\Utils.lua:122>
[string "@Interface\AddOns\Farmer\classes\CallbackHandler.lua"]:22: in function `__callCallbacks'
[string "@Interface\AddOns\Farmer\classes\CallbackHandler.lua"]:48: in function `call'
[string "@Interface\AddOns\Farmer\core\Events.lua"]:10: in function <Interface\AddOns\Farmer\core\Events.lua:9>

**Comment by syndenbock** [comment] 2022-12-15 23:57
I have just released a new version 3.16.6 where this error should no longer occur but print a debug message with an item id instead. Please let me know said item id so I can look into a possible issue with some items.

**Comment by WorkPixels** [comment] 2022-12-16 01:59
So far no errors with the update.

**Comment by syndenbock** [comment] 2022-12-16 02:08
And is there any message in the chat after logging in? Because unless the cause of the error magically vanished, a message should be printed stating something about an item link could not be found for an item id.

**Comment by WorkPixels** [comment] 2022-12-16 02:13
This is the only thing I see.

Farmer: No link found for item id 41164.

**Comment by WorkPixels** [comment] 2022-12-16 02:14
Mammoth Cutters = 41164

**Comment by syndenbock** [comment] 2022-12-16 02:15
I assume you have Mammoth Cutters equipped as ammo?
If so, can you unequip any ammo, /reload and check if a message is printed still?

**Comment by WorkPixels** [comment] 2022-12-16 16:21
I wasn't able to unequip the ammo. I logged into another character. It seems that it's not able to count equipped ammo.

Farmer: No link found for item id 32883.
Felbane Slugs = 32883

**Comment by WorkPixels** [comment] 2022-12-16 16:36
When I log in to any character without ammo equipped I don't see any errors.

**Comment by syndenbock** [comment] 2022-12-16 18:25
Thanks a ton for the input! I don't have a classic character with ammo so I couldn't test this myself but now I at least know what causes the error and can look into finding a fix.

**Comment by syndenbock** [comment] 2022-12-16 20:45
The fix actually is trivial, I had assumed equipped ammo is removed from the bags but it's just a visual slot.
So the error is fixed by simply not checking the equipped ammo slot.

**Comment by syndenbock** [comment] 2022-12-16 21:44
Just to confirm: The message no longer pops up in version 3.16.7, correct?

**Comment by WorkPixels** [comment] 2022-12-17 01:37
I do not see any errors

**Closed as completed** 2024-06-10 17:29 UTC
