### ISSUE TITLE
looting items are broken after ulduar patch (wotlk classic)

### ISSUE THREAD

**Issue by dh-harald** [syndenbock/Farmer#16] opened 2023-01-20 12:16 UTC
Hi,

It looks, not updating every time when I loot something. sometimes it's working but usually it's not.
for example I'm looting couple of items in a dungeon and not showing them, and after I HSing/teleporting to Dalaran, it shows all the items bulky.
Maybe some event missing, like known BAG_UPDATE_DELAYED

**Comment by syndenbock** [comment] 2023-01-20 13:23
People have reported this issue already but I couldn't reproduce it while questing, so narrowing it down to dungeons is very helpful already. Unfortunately I only have a level 7 character on WotlK classic so I cannot go into dungeons to check it myself.

That indeed sounds like BAG_UPDATE_DELAYED is not being fired by the game because that's the event I'm using to check what changed in the bags. Do you have any means to check if the event is fired while in dungeons?

**Comment by syndenbock** [comment] 2023-01-20 13:27
I have looked around on the UIDev Discord and people are reporting that the game does not reliably fire BAG_UPDATE_DELAYED in the current WotlK classic patch. This hopefully gets fixed by Blizzard because I don't think there is a reliable workaround.

**Comment by dh-harald** [comment] 2023-01-20 15:39
I runned etrace, and it looks, the BAG_UPDATE_DELAYED event is still missing... I tried to debug it, but after 3 BAG_UPDATE there was no BAG_UPDATE_DELAYED (and the addon didn't showed any loots)

**Comment by syndenbock** [comment] 2023-01-21 00:33
I implemented a workaround that should hopefully work. Once Blizzard fixes the issue on their side, I'll remove the workaround and close this issue.

**Comment by syndenbock** [comment] 2024-08-15 16:41
Closing this issue because BAG_UPDATE_DELAYED properly fires on classic again (for a while now already).

**Closed as completed by syndenbock** 2024-08-15 16:41 UTC
